version: '3.3'

services:

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow

  app:
    image: imixs/imixs-microservice
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/workflow"
      
      IMIXS_REGISTRY_API: "http://registry:8080/api"
      IMIXS_AUTH_METHOD: "BASIC"
      IMIXS_AUTH_USERID: "admin"
      IMIXS_AUTH_SECRET: "adminadmin"
      IMIXS_INTERVAL: 10000
      IMIXS_REGISTRY_INDEX_ENABLED: "true"
      IMIXS-REGISTRY_INDEX_FIELDS: ""
      IMIXS_REGISTRY_AUTOREGISTER_INTERVAL: 4000
      IMIXS_API: "http://app:8080/api"
      
      BATCH_PROCESSOR_ENABLED: "true"
      BATCH_PROCESSOR_INTERVAL: "500"
      BATCH_PROCESSOR_INITIALDELAY: "2000"      
      
      
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - ~/git/imixs-microservice/src/model/:/home/imixs/model/
      # Uncomment the followign lines to provide a auto-deployment directory for development   
      #- ~/git/imixs-microservice/imixs-microservice-app/src/docker/deployments:/opt/wildfly/standalone/deployments/
    depends_on:
      - registry
      - db
      - solr



  registry:
    image: imixs/imixs-registry
    environment:
      WILDFLY_PASS: adminadmin
      TZ: "Europe/Berlin"
      
      INDEX_INTERVAL: 2000
      IMIXS_AUTH_METHOD: "BASIC"
      IMIXS_AUTH_USERID: "admin"
      IMIXS_AUTH_SECRET: "adminadmin"
      IMIXS_AUTH_PROPAGATION: "true"
            
      SOLR_API: "http://solr:8983" 
      SOLR_CORE: "registry"

      IMIXS_REGISTRY_INDEX_INTERVAL: 2000
      IMIXS_REGISTRY_INDEX_FIELDS: "oap.screen"
       
    ports:
      - "8081:8080"
    depends_on:
      - solr


  solr:
    image: solr:8.2
    ports:
      - "8983:8983"      
    #volumes:
    #  - solrdata:/opt/solr/server/solr/imixs-workflow
    # Create two different cores!
    entrypoint:
      - bash
      - "-c"
      - "precreate-core registry; exec solr -f"
 