version: '3.3'

services:

  db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow

  app:
    image: imixs/imixs-microservice
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://db/workflow"
      
      MODEL_DEFAULT_DATA: "/home/imixs/model/ticket-en-1.0.0.bpmn;/home/imixs/model/order-en-1.0.0.bpmn"
      MODEL_DEFAULT_DATA_OVERWRITE: "true"
      IMIXS_REGISTRY_API: "http://registry:8080/api"
      IMIXS_AUTH_METHOD: "BASIC"
      IMIXS_AUTH_USERID: "admin"
      IMIXS_AUTH_SECRET: "adminadmin"
      IMIXS_INTERVAL: 10000
      IMIXS_REGISTRY_INDEX_ENABLED: "false"
      IMIXS-REGISTRY_INDEX_FIELDS: ""
      #IMIXS_REGISTRY_AUTOREGISTER_INTERVAL: 120000
      IMIXS_API: "http://app:8080/api"
      
      BATCH_PROCESSOR_ENABLED: "true"
      BATCH_PROCESSOR_INTERVAL: 2000
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"    
    volumes:
      - ~/git/imixs-microservice/src/model/:/home/imixs/model/
      # Uncomment the followign lines to provide a auto-deployment directory for development   
      #- ~/git/imixs-microservice/imixs-microservice-app/src/docker/deployments:/opt/wildfly/standalone/deployments/
    depends_on:
      - registry
      - db
      - solr



  registry:
    image: imixs/imixs-registry
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      TZ: "Europe/Berlin"
      
      INDEX_INTERVAL: 2000
      IMIXS_AUTH_METHOD: "BASIC"
      IMIXS_AUTH_USERID: "admin"
      IMIXS_AUTH_SECRET: "adminadmin"
      
      
      SOLR_API: "http://solr:8983" 
      SOLR_CORE: "registry"
      
      #IMIXS_AUTH_METHOD: "JWT"
      #IMIXS_AUTH_USERID: "admin"
      #IMIXS_AUTH_SECRET: "secret"
      
            
       
    ports:
      - "8081:8080"
      - "9991:9990"
      - "8788:8787"    

    #volumes:
      # Uncomment the followign lines to provide a auto-deployment directory for development   
      #- ~/git/imixs-microservice/imixs-microservice-registry/src/docker/deployments:/opt/wildfly/standalone/deployments/
      
    depends_on:
      - solr



  solr:
    image: solr:8.2
    ports:
      - "8983:8983"      
    #volumes:
    #  - solrdata:/opt/solr/server/solr/imixs-workflow
    # Create two different cores!
    entrypoint:
      - bash
      - "-c"
      - "precreate-core registry; exec solr -f"
 